### ISSUE TITLE
Use as CLI

### ISSUE THREAD

**Issue by 2xAA** [Jam3/msdf-bmfont#20]
Hey,

Thanks for this great library!

It would be great to run this as a CLI - do you think there's scope in this project for that?

Thanks,
Sam

**Comment by ethernet8023** [comment]
Hey! This project has been in feature stasis for a long time, I would suggest checking out the fork at https://github.com/soimy/msdf-bmfont-xml which has many more features & a powerful cli interface :)

**Comment by 2xAA** [comment]
Awesome, will do - thanks again :)
