### ISSUE TITLE
Help to run the examples

### ISSUE THREAD

**Issue by ammoises** [Jam3/msdf-bmfont#8]
I am trying to run examples but when run the example "test-render.js" the browser get me the next error:

Uncaught Error: Module name "three-bmfont-text" has not been loaded yet for context: _. Use require([])

And reviewing your source don´t find file the three-bmfont-text.js

Where I can get that file? or
Where I can get the complete project with all functional examples?

**Comment by arilotter** [comment]
Hi, `three-bmfont-text` is a dev dependency. Make sure you run `npm install` in the project directory before trying to run the examples.

**Comment by arilotter** [comment]
Actually, your comment `the browser` makes me think you're trying to run msdf-bmfont in-browser.
Currently, they need to be run offline with node.js.
Additionally, running the tests requires [`devtool`](https://www.npmjs.com/package/devtool) (`npm install -g devtool), which should really be a dev dependency or removed entirely. I'll open an issue for that.
